in_game_music_queue = ['https://www.youtube.com/watch?v=K9840msu1CM',
'https://www.youtube.com/watch?v=Hmy-fnqBFTE', 
'https://www.youtube.com/watch?v=hvJ7n2GbOUQ', 
'https://www.youtube.com/watch?v=QnfUnVQ1Sdc', 
'https://www.youtube.com/watch?v=FZbxyhwz3ls', 
'https://www.youtube.com/watch?v=hsEhV8AiDp4', 
'https://www.youtube.com/watch?v=ZUj6k5LQrJ0',
'https://www.youtube.com/watch?v=g3zHdtGFN34',
'https://www.youtube.com/watch?v=uEvN7JSCIyk',
'https://www.youtube.com/watch?v=y28u5HiG0QM',
'https://www.youtube.com/watch?v=i5Cyi_4GIeU',
]